---
- hosts: vagrant
  sudo: True
  gather_facts: yes

  tasks:
    - name: Ensure the system can use the HTTPS transport for APT
      stat: path=/usr/lib/apt/methods/https
      register: apt_https_transport

    - name: Install HTTPS transport for APT
      apt: pkg=apt-transport-https state=installed update_cache=yes cache_valid_time=86400
      when: not apt_https_transport.stat.exists

    - name: Save installed apt keys
      shell: apt-key list
      register: apt_key_list
      changed_when: False

    - name: Import the NodeSource GPG key into apt
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
      when: apt_key_list.stdout.find('NodeSource') == -1

    - name: Add NodeSource deb repository
      apt_repository: repo='deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main' state=present update_cache=yes

    - name: Install Node.js
      apt: pkg=nodejs=0.10.* state=installed update_cache=yes cache_valid_time=86400

    - name: Install npm
      npm: name=npm global=yes state=present

    - name: Install API tools for libgrib
      apt: pkg=libgrib-api-tools state=installed

    - name: Install misc tools
      apt: pkg={{ item }} state=latest
      with_items:
        - git
        - curl
